// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: proto/query.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastleFareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Castle string `protobuf:"bytes,1,opt,name=castle,proto3" json:"castle,omitempty"`
}

func (x *CastleFareRequest) Reset() {
	*x = CastleFareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastleFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastleFareRequest) ProtoMessage() {}

func (x *CastleFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastleFareRequest.ProtoReflect.Descriptor instead.
func (*CastleFareRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{0}
}

func (x *CastleFareRequest) GetCastle() string {
	if x != nil {
		return x.Castle
	}
	return ""
}

type CastleFareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fare float32 `protobuf:"fixed32,1,opt,name=fare,proto3" json:"fare,omitempty"`
}

func (x *CastleFareResponse) Reset() {
	*x = CastleFareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastleFareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastleFareResponse) ProtoMessage() {}

func (x *CastleFareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastleFareResponse.ProtoReflect.Descriptor instead.
func (*CastleFareResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{1}
}

func (x *CastleFareResponse) GetFare() float32 {
	if x != nil {
		return x.Fare
	}
	return 0
}

type CastleInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Castle string `protobuf:"bytes,1,opt,name=castle,proto3" json:"castle,omitempty"`
	Day    string `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *CastleInfoRequest) Reset() {
	*x = CastleInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastleInfoRequest) ProtoMessage() {}

func (x *CastleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastleInfoRequest.ProtoReflect.Descriptor instead.
func (*CastleInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{2}
}

func (x *CastleInfoRequest) GetCastle() string {
	if x != nil {
		return x.Castle
	}
	return ""
}

func (x *CastleInfoRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type CastleInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOpen      bool   `protobuf:"varint,1,opt,name=isOpen,proto3" json:"isOpen,omitempty"`
	OpenTime    string `protobuf:"bytes,2,opt,name=openTime,proto3" json:"openTime,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CastleInfoResponse) Reset() {
	*x = CastleInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastleInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastleInfoResponse) ProtoMessage() {}

func (x *CastleInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastleInfoResponse.ProtoReflect.Descriptor instead.
func (*CastleInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{3}
}

func (x *CastleInfoResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *CastleInfoResponse) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *CastleInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BusFareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Noc     string `protobuf:"bytes,1,opt,name=noc,proto3" json:"noc,omitempty"`
	BusName string `protobuf:"bytes,2,opt,name=busName,proto3" json:"busName,omitempty"`
}

func (x *BusFareRequest) Reset() {
	*x = BusFareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusFareRequest) ProtoMessage() {}

func (x *BusFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusFareRequest.ProtoReflect.Descriptor instead.
func (*BusFareRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{4}
}

func (x *BusFareRequest) GetNoc() string {
	if x != nil {
		return x.Noc
	}
	return ""
}

func (x *BusFareRequest) GetBusName() string {
	if x != nil {
		return x.BusName
	}
	return ""
}

type BusFareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fare float64 `protobuf:"fixed64,1,opt,name=fare,proto3" json:"fare,omitempty"`
}

func (x *BusFareResponse) Reset() {
	*x = BusFareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusFareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusFareResponse) ProtoMessage() {}

func (x *BusFareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusFareResponse.ProtoReflect.Descriptor instead.
func (*BusFareResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{5}
}

func (x *BusFareResponse) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

type TrainFareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainName string `protobuf:"bytes,1,opt,name=trainName,proto3" json:"trainName,omitempty"`
}

func (x *TrainFareRequest) Reset() {
	*x = TrainFareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainFareRequest) ProtoMessage() {}

func (x *TrainFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainFareRequest.ProtoReflect.Descriptor instead.
func (*TrainFareRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{6}
}

func (x *TrainFareRequest) GetTrainName() string {
	if x != nil {
		return x.TrainName
	}
	return ""
}

type TrainFareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fare float32 `protobuf:"fixed32,1,opt,name=fare,proto3" json:"fare,omitempty"`
}

func (x *TrainFareResponse) Reset() {
	*x = TrainFareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainFareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainFareResponse) ProtoMessage() {}

func (x *TrainFareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainFareResponse.ProtoReflect.Descriptor instead.
func (*TrainFareResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{7}
}

func (x *TrainFareResponse) GetFare() float32 {
	if x != nil {
		return x.Fare
	}
	return 0
}

type RouteToCastleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original    string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *RouteToCastleRequest) Reset() {
	*x = RouteToCastleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteToCastleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteToCastleRequest) ProtoMessage() {}

func (x *RouteToCastleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteToCastleRequest.ProtoReflect.Descriptor instead.
func (*RouteToCastleRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{8}
}

func (x *RouteToCastleRequest) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *RouteToCastleRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type RouteToCastleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original      string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Destination   string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	TransportName string `protobuf:"bytes,4,opt,name=transportName,proto3" json:"transportName,omitempty"`
	Noc           string `protobuf:"bytes,6,opt,name=noc,proto3" json:"noc,omitempty"` //not operator ID. please give noc of this bus if type is bus.
	Step          int32  `protobuf:"varint,7,opt,name=step,proto3" json:"step,omitempty"`
	Comment       string `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *RouteToCastleInfo) Reset() {
	*x = RouteToCastleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteToCastleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteToCastleInfo) ProtoMessage() {}

func (x *RouteToCastleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteToCastleInfo.ProtoReflect.Descriptor instead.
func (*RouteToCastleInfo) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{9}
}

func (x *RouteToCastleInfo) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *RouteToCastleInfo) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteToCastleInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RouteToCastleInfo) GetTransportName() string {
	if x != nil {
		return x.TransportName
	}
	return ""
}

func (x *RouteToCastleInfo) GetNoc() string {
	if x != nil {
		return x.Noc
	}
	return ""
}

func (x *RouteToCastleInfo) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *RouteToCastleInfo) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RouteToCastleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteID int32                `protobuf:"varint,1,opt,name=routeID,proto3" json:"routeID,omitempty"`
	Info    []*RouteToCastleInfo `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *RouteToCastleResponse) Reset() {
	*x = RouteToCastleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteToCastleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteToCastleResponse) ProtoMessage() {}

func (x *RouteToCastleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteToCastleResponse.ProtoReflect.Descriptor instead.
func (*RouteToCastleResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{10}
}

func (x *RouteToCastleResponse) GetRouteID() int32 {
	if x != nil {
		return x.RouteID
	}
	return 0
}

func (x *RouteToCastleResponse) GetInfo() []*RouteToCastleInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StartTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteID int32 `protobuf:"varint,1,opt,name=routeID,proto3" json:"routeID,omitempty"`
	Day     int32 `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *StartTimeRequest) Reset() {
	*x = StartTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTimeRequest) ProtoMessage() {}

func (x *StartTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTimeRequest.ProtoReflect.Descriptor instead.
func (*StartTimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{11}
}

func (x *StartTimeRequest) GetRouteID() int32 {
	if x != nil {
		return x.RouteID
	}
	return 0
}

func (x *StartTimeRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type StartTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time []string `protobuf:"bytes,1,rep,name=time,proto3" json:"time,omitempty"`
}

func (x *StartTimeResponse) Reset() {
	*x = StartTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_query_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTimeResponse) ProtoMessage() {}

func (x *StartTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTimeResponse.ProtoReflect.Descriptor instead.
func (*StartTimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{12}
}

func (x *StartTimeResponse) GetTime() []string {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_proto_query_proto protoreflect.FileDescriptor

var file_proto_query_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x11, 0x63, 0x61,
	0x73, 0x74, 0x6c, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x63, 0x61, 0x73, 0x74, 0x6c,
	0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x66, 0x61, 0x72,
	0x65, 0x22, 0x3d, 0x0a, 0x11, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79,
	0x22, 0x6a, 0x0a, 0x12, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x0e,
	0x62, 0x75, 0x73, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x6f, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x6f, 0x63,
	0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x62, 0x75,
	0x73, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x66, 0x61, 0x72,
	0x65, 0x22, 0x30, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x66, 0x61, 0x72, 0x65, 0x22, 0x54, 0x0a, 0x14,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x6f, 0x43, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xcb, 0x01, 0x0a, 0x11, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x6f, 0x43, 0x61,
	0x73, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x5f, 0x0a, 0x15, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x6f, 0x43, 0x61, 0x73, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x54,
	0x6f, 0x43, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x3e, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x44, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61,
	0x79, 0x22, 0x27, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x32, 0xb8, 0x03, 0x0a, 0x0c, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x46, 0x61, 0x72, 0x65, 0x12, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x46, 0x61, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x73, 0x74,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x61, 0x73, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x42, 0x75, 0x73, 0x46, 0x61, 0x72, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x75, 0x73, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x75, 0x73, 0x46, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x61, 0x72, 0x65, 0x12, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4f, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x6f, 0x43,
	0x61, 0x73, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x54, 0x6f, 0x43, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x54, 0x6f, 0x43, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x43, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_query_proto_rawDescOnce sync.Once
	file_proto_query_proto_rawDescData = file_proto_query_proto_rawDesc
)

func file_proto_query_proto_rawDescGZIP() []byte {
	file_proto_query_proto_rawDescOnce.Do(func() {
		file_proto_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_query_proto_rawDescData)
	})
	return file_proto_query_proto_rawDescData
}

var file_proto_query_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_query_proto_goTypes = []interface{}{
	(*CastleFareRequest)(nil),     // 0: proto.castleFareRequest
	(*CastleFareResponse)(nil),    // 1: proto.castleFareResponse
	(*CastleInfoRequest)(nil),     // 2: proto.castleInfoRequest
	(*CastleInfoResponse)(nil),    // 3: proto.castleInfoResponse
	(*BusFareRequest)(nil),        // 4: proto.busFareRequest
	(*BusFareResponse)(nil),       // 5: proto.busFareResponse
	(*TrainFareRequest)(nil),      // 6: proto.trainFareRequest
	(*TrainFareResponse)(nil),     // 7: proto.trainFareResponse
	(*RouteToCastleRequest)(nil),  // 8: proto.routeToCastleRequest
	(*RouteToCastleInfo)(nil),     // 9: proto.routeToCastleInfo
	(*RouteToCastleResponse)(nil), // 10: proto.routeToCastleResponse
	(*StartTimeRequest)(nil),      // 11: proto.startTimeRequest
	(*StartTimeResponse)(nil),     // 12: proto.startTimeResponse
}
var file_proto_query_proto_depIdxs = []int32{
	9,  // 0: proto.routeToCastleResponse.info:type_name -> proto.routeToCastleInfo
	0,  // 1: proto.QueryService.QueryCastleFare:input_type -> proto.castleFareRequest
	2,  // 2: proto.QueryService.QueryCastleInfo:input_type -> proto.castleInfoRequest
	4,  // 3: proto.QueryService.QueryBusFare:input_type -> proto.busFareRequest
	6,  // 4: proto.QueryService.QueryTrainFare:input_type -> proto.trainFareRequest
	8,  // 5: proto.QueryService.QueryRouteToCastle:input_type -> proto.routeToCastleRequest
	11, // 6: proto.QueryService.QueryStartTime:input_type -> proto.startTimeRequest
	1,  // 7: proto.QueryService.QueryCastleFare:output_type -> proto.castleFareResponse
	3,  // 8: proto.QueryService.QueryCastleInfo:output_type -> proto.castleInfoResponse
	5,  // 9: proto.QueryService.QueryBusFare:output_type -> proto.busFareResponse
	7,  // 10: proto.QueryService.QueryTrainFare:output_type -> proto.trainFareResponse
	10, // 11: proto.QueryService.QueryRouteToCastle:output_type -> proto.routeToCastleResponse
	12, // 12: proto.QueryService.QueryStartTime:output_type -> proto.startTimeResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_query_proto_init() }
func file_proto_query_proto_init() {
	if File_proto_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastleFareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastleFareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastleInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastleInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusFareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusFareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainFareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainFareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteToCastleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteToCastleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteToCastleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_query_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_query_proto_goTypes,
		DependencyIndexes: file_proto_query_proto_depIdxs,
		MessageInfos:      file_proto_query_proto_msgTypes,
	}.Build()
	File_proto_query_proto = out.File
	file_proto_query_proto_rawDesc = nil
	file_proto_query_proto_goTypes = nil
	file_proto_query_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryServiceClient interface {
	QueryCastleFare(ctx context.Context, in *CastleFareRequest, opts ...grpc.CallOption) (*CastleFareResponse, error)
	QueryCastleInfo(ctx context.Context, in *CastleInfoRequest, opts ...grpc.CallOption) (*CastleInfoResponse, error)
	QueryBusFare(ctx context.Context, in *BusFareRequest, opts ...grpc.CallOption) (*BusFareResponse, error)
	QueryTrainFare(ctx context.Context, in *TrainFareRequest, opts ...grpc.CallOption) (*TrainFareResponse, error)
	QueryRouteToCastle(ctx context.Context, in *RouteToCastleRequest, opts ...grpc.CallOption) (*RouteToCastleResponse, error)
	QueryStartTime(ctx context.Context, in *StartTimeRequest, opts ...grpc.CallOption) (*StartTimeResponse, error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) QueryCastleFare(ctx context.Context, in *CastleFareRequest, opts ...grpc.CallOption) (*CastleFareResponse, error) {
	out := new(CastleFareResponse)
	err := c.cc.Invoke(ctx, "/proto.QueryService/QueryCastleFare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryCastleInfo(ctx context.Context, in *CastleInfoRequest, opts ...grpc.CallOption) (*CastleInfoResponse, error) {
	out := new(CastleInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.QueryService/QueryCastleInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryBusFare(ctx context.Context, in *BusFareRequest, opts ...grpc.CallOption) (*BusFareResponse, error) {
	out := new(BusFareResponse)
	err := c.cc.Invoke(ctx, "/proto.QueryService/QueryBusFare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryTrainFare(ctx context.Context, in *TrainFareRequest, opts ...grpc.CallOption) (*TrainFareResponse, error) {
	out := new(TrainFareResponse)
	err := c.cc.Invoke(ctx, "/proto.QueryService/QueryTrainFare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryRouteToCastle(ctx context.Context, in *RouteToCastleRequest, opts ...grpc.CallOption) (*RouteToCastleResponse, error) {
	out := new(RouteToCastleResponse)
	err := c.cc.Invoke(ctx, "/proto.QueryService/QueryRouteToCastle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) QueryStartTime(ctx context.Context, in *StartTimeRequest, opts ...grpc.CallOption) (*StartTimeResponse, error) {
	out := new(StartTimeResponse)
	err := c.cc.Invoke(ctx, "/proto.QueryService/QueryStartTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
type QueryServiceServer interface {
	QueryCastleFare(context.Context, *CastleFareRequest) (*CastleFareResponse, error)
	QueryCastleInfo(context.Context, *CastleInfoRequest) (*CastleInfoResponse, error)
	QueryBusFare(context.Context, *BusFareRequest) (*BusFareResponse, error)
	QueryTrainFare(context.Context, *TrainFareRequest) (*TrainFareResponse, error)
	QueryRouteToCastle(context.Context, *RouteToCastleRequest) (*RouteToCastleResponse, error)
	QueryStartTime(context.Context, *StartTimeRequest) (*StartTimeResponse, error)
}

// UnimplementedQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (*UnimplementedQueryServiceServer) QueryCastleFare(context.Context, *CastleFareRequest) (*CastleFareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCastleFare not implemented")
}
func (*UnimplementedQueryServiceServer) QueryCastleInfo(context.Context, *CastleInfoRequest) (*CastleInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCastleInfo not implemented")
}
func (*UnimplementedQueryServiceServer) QueryBusFare(context.Context, *BusFareRequest) (*BusFareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBusFare not implemented")
}
func (*UnimplementedQueryServiceServer) QueryTrainFare(context.Context, *TrainFareRequest) (*TrainFareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTrainFare not implemented")
}
func (*UnimplementedQueryServiceServer) QueryRouteToCastle(context.Context, *RouteToCastleRequest) (*RouteToCastleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRouteToCastle not implemented")
}
func (*UnimplementedQueryServiceServer) QueryStartTime(context.Context, *StartTimeRequest) (*StartTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStartTime not implemented")
}

func RegisterQueryServiceServer(s *grpc.Server, srv QueryServiceServer) {
	s.RegisterService(&_QueryService_serviceDesc, srv)
}

func _QueryService_QueryCastleFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastleFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryCastleFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QueryService/QueryCastleFare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryCastleFare(ctx, req.(*CastleFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryCastleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryCastleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QueryService/QueryCastleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryCastleInfo(ctx, req.(*CastleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryBusFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryBusFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QueryService/QueryBusFare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryBusFare(ctx, req.(*BusFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryTrainFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryTrainFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QueryService/QueryTrainFare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryTrainFare(ctx, req.(*TrainFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryRouteToCastle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteToCastleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryRouteToCastle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QueryService/QueryRouteToCastle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryRouteToCastle(ctx, req.(*RouteToCastleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_QueryStartTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).QueryStartTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QueryService/QueryStartTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).QueryStartTime(ctx, req.(*StartTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryCastleFare",
			Handler:    _QueryService_QueryCastleFare_Handler,
		},
		{
			MethodName: "QueryCastleInfo",
			Handler:    _QueryService_QueryCastleInfo_Handler,
		},
		{
			MethodName: "QueryBusFare",
			Handler:    _QueryService_QueryBusFare_Handler,
		},
		{
			MethodName: "QueryTrainFare",
			Handler:    _QueryService_QueryTrainFare_Handler,
		},
		{
			MethodName: "QueryRouteToCastle",
			Handler:    _QueryService_QueryRouteToCastle_Handler,
		},
		{
			MethodName: "QueryStartTime",
			Handler:    _QueryService_QueryStartTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/query.proto",
}
